import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "coverage/**",
      // Auto-generated by `next build`/`next dev` — not hand-authored.
      "next-env.d.ts",
      // Pending rework under ticket 19 (openRouterHelper 改造 + 測試) — not
      // touched here so that work happens test-first, not as a lint sweep.
      "openRouterHelper.ts",
    ],
  },
];

export default eslintConfig;
