import { chromium } from "playwright";
const base = "http://localhost:3210";
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: "en", userAgent: UA });
const p = await ctx.newPage();
await p.goto(`${base}/en/parts`, { waitUntil: "networkidle", timeout: 120000 });
await p.locator("table tbody a").first().click();
await p.waitForSelector("dialog[open]", { timeout: 30000 });
await p.waitForTimeout(500);
console.log("url", p.url());
console.log("close label", await p.locator("dialog[open] button").first().getAttribute("aria-label"));
const links = await p.locator("dialog[open] footer a").evaluateAll(as => as.map(a => [a.textContent.trim(), a.getAttribute("href")]));
console.log("footer", JSON.stringify(links));
await p.locator("dialog[open] footer a").first().click();
await p.waitForLoadState("load");
await p.waitForTimeout(500);
console.log("after full page", p.url(), "dialogs", await p.locator("dialog").count(), "h1", await p.locator("main h1").textContent());
// reduced motion + keyboard tab cycle stays inside
const ctx2 = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: "zh-TW", userAgent: UA, reducedMotion: "reduce" });
const q = await ctx2.newPage();
await q.goto(`${base}/parts`, { waitUntil: "networkidle", timeout: 120000 });
await q.locator("table tbody a").first().click();
await q.waitForSelector("dialog[open]", { timeout: 30000 });
await q.waitForTimeout(300);
const anim = await q.evaluate(() => getComputedStyle(document.querySelector("dialog[open] > div"), "::after").animationName);
console.log("reduced-motion ring animation:", anim);
for (let i = 0; i < 40; i++) await q.keyboard.press("Tab");
console.log("focus after 40 tabs inside dialog:", await q.evaluate(() => !!document.activeElement.closest("dialog")));
await browser.close();
